test:
	./c2x -v
#	./c2x -s test_splitter -i toto.h dest_test src_test

install:
	mkdir -p ~/bin
	cp c2x $(HOME)/bin/
	cp c2x.c $(HOME)/bin/.c2x.c
	cp c2x.h $(HOME)/bin/.c2x.h
	cp main.c $(HOME)/bin/.main.c
